### ISSUE TITLE
How to contact you

### ISSUE THREAD

**Issue by egeu5** [flyve-mdm/doc#17]
I know that this place is not really the right one for my question but I am not able to contact you. I tried it with the web formular and by mail but did not get a response for a month.

We are thinking about to use flyve-mdm at school. In our first step we need to integrate about 100 devices, growing up year by year to about 1.000. Please send us a list with the costs of the saas. Furthermore we need to know how powerful the server for those project hast to be.

On you're website you say that iOs support is coming next. Could you give us a timeline for those project?
Thank you,
Chris

**Comment by ChrisinCA** [comment]
Dear Egeu5,
I'm so glad to be in contact with you. Thank you for your interest on Flyve MDM. 
My apologies to not answers you before. 
Can you give me your email ?

I look forward hearing from you.

Kind regards, 
Christelle

**Comment by ChrisinCA** [comment]
If you prefer you can write me on cinacio@teclib.com

**Comment by egeu5** [comment]
Thank you for the fast feedback. This question can be closed :-)

**Comment by ChrisinCA** [comment]
Hi 

I'm so sorry for the delay. I would like to know if we answer to your questions? 
I think I answer you there is few minutes to over email. 

Can we have a call this week, Thursday for exemple? 

Have a good day. 




Christelle INACIO 
Channel Manager 
cinacio@teclib.com 

GLPI Project | GLPI Network | GLPI Telemetry 

----- Mail original -----

De: "egeu5" <notifications@github.com> 
À: "flyve-mdm/doc" <doc@noreply.github.com> 
Cc: "ChrisinCA" <cinacio@teclib.com>, "Assign" <assign@noreply.github.com> 
Envoyé: Mercredi 7 Novembre 2018 09:49:37 
Objet: Re: [flyve-mdm/doc] How to contact you (#17) 



Thank you for the fast feedback. This question can be closed :-)

**Comment by egeu5** [comment]
Thank you for you're quick reply. First we want to test the software - but the demo-sites are not working. Will this get fixed in the next time or had I to set up a docker environment?

**Comment by Naylin15** [comment]
Hi @egeu5 

The demo site is working, you can request your credentials through our website [Flyve MDM](https://flyve-mdm.com/)

- Click on **Ask for Demo** at the first section
- Fill the formulaire and you'll receive your credentials in your email
- Then access the [Demo site](https://demo-dashboard.flyve.org/) and you'll be able to start using Flyve MDM!

Have a good day!
