### ISSUE TITLE
UML Diagrams

### ISSUE THREAD

**Issue by Naylin15** [flyve-mdm/doc#18]
# Missing Information
We must create sequence diagrams of every process for both the plugin and agent

- [x] Enrollment
- [x] Status Online/Offline
- [x] Unenrollment
- [x] Implementation of policies
- [x] Ping request
- [x] Geolocation request
- [x] Lock request
- [x] Wipe request

# Potential Locations

How it works section

**Comment by btry** [comment]
H

I think this should e in the developers documentation. How it works needs something with less details.

**Comment by Naylin15** [comment]
Hi,

I'll add it then in the Contributing section

Merci

**Comment by Naylin15** [comment]
I'm searching how to fix this issue in RTD

![captura de pantalla 2018-11-26 a la s 3 45 23 p m](https://user-images.githubusercontent.com/30867977/49038235-be002580-f192-11e8-9571-207f18829c3f.png)
